GNAT_SOURCES= \
  gnat_ugn.texi \
  krunch.ads \
  krunch.adb \
  prj-pars.ads \
  prj-pars.adb \
  impunit.adb \
  gnat_style.css

list-sources:
	@echo $(GNAT_SOURCES)

list-sources-regexp:
	@echo -n "("
	@for f in $(GNAT_SOURCES); do \
	  if [ "$$f" = "gnat_style.css" ]; then \
	    echo "$$f)"; \
	  else \
	    echo -n "$$f|"; \
	  fi; \
	done
