export TP_TASKING = No_Tasking

# How to build gnatlib
export GNATLIB_LIBRARY_TYPE=static
#export GNATLIB_LIBRARY_TYPE=relocatable

default build compile link ada c c++ clean internal-clean :
	$(MAKE) -s -f Makefile.gps $@

