#!/bin/sh
valgrind="valgrind -v --suppressions=valgrind-python.supp --suppressions=gps.supp --track-fds=yes"

# use --db-attach=yes to attach to a debugger for every error found


## See http://www.lrz-muenchen.de/services/software/programmierung/valgrind/html_3.0/ms-manual.html

## Modes that can be used when running this script:
## memcheck : check pointers
## leaks:   : check memory leaks
## massif   : check heap usage
## addrcheck: check pointers usage, same as memcheck but doesn't do
##            "undefined-value checks". Twice as fast though


mode=${1:-memcheck}
shift

case $mode in
   leaks)    args="--tool=memcheck --leak-check=full --show-reachable=yes" ;;
   memcheck) args="--tool=memcheck";;
   massif)   args="--tool=massif --depth=5 --format=html --alloc-fn=__gnat_malloc \
                   --alloc-fn=PyObject_Malloc --alloc-fn=g_malloc --alloc-fn=__gnat_realloc \
                   --alloc-fn=g_realloc --alloc-fn=g_try_malloc --alloc-fn=g_malloc0 \
                   --alloc-fn=g_mem_chunk_alloc --alloc-fn=_PyObject_GC_Malloc" ;;
esac  

$valgrind $args ./obj/gps "$@" 2>&1 | tee log
