# GVD_SRC is automatically defined in Makefile.common
C_FILES=${GVD_SRC}/pixmaps/pixmaps.c ${PRJ_EDITOR_SRC}/src/prj_pixmaps.c
MAIN=hypergrep_main
MODULES=kernel gvd gtkada prj_editor gnat common glide src_editor
MODULE_LIB=${GVD_SRC}/gnat/gexpect_tty.o
NO_STYLE_FILES=

include ../../Makefile.common
