
C_FILES=${GVD_SRC}/pixmaps/pixmaps.c ${PRJ_EDITOR_SRC}/src/prj_pixmaps.c ${PRJ_EDITOR_SRC}/src/env.c
MAIN=glide2 glide
MODULES=gtkada gvd prj_editor gnat common hypergrep vdiff
MODULE_LIB=${GVD_SRC}/gnat/gexpect_tty.o
NO_STYLE_FILES=

include ../../Makefile.common
