with Gtk.Window; use Gtk.Window;
with Gtk.Box; use Gtk.Box;
with Gtk.Menu_Bar; use Gtk.Menu_Bar;
with Gtk.Menu_Item; use Gtk.Menu_Item;
with Gtk.Menu; use Gtk.Menu;
with Gtk.Paned; use Gtk.Paned;
with Gtk.Handle_Box; use Gtk.Handle_Box;
with Gtk.Toolbar; use Gtk.Toolbar;
with Gtk.Widget; use Gtk.Widget;
with Gtk.Notebook; use Gtk.Notebook;
with Gtk.Frame; use Gtk.Frame;
with Gtk.Pixmap; use Gtk.Pixmap;
with Gtk.Label; use Gtk.Label;
with Gtk.Scrolled_Window; use Gtk.Scrolled_Window;
with Gtk.Ctree; use Gtk.Ctree;
with Gtk.Clist; use Gtk.Clist;
with Gtk.Status_Bar; use Gtk.Status_Bar;
with Gtk.Combo; use Gtk.Combo;
with Gtk.GEntry; use Gtk.GEntry;
with Gtk.Button; use Gtk.Button;
package Gui_Builder_Pkg is

   type Gui_Builder_Record is new Gtk_Window_Record with record
      Vbox4 : Gtk_Vbox;
      Menubar1 : Gtk_Menu_Bar;
      Menuitem13 : Gtk_Menu_Item;
      Menu1 : Gtk_Menu;
      Menuitem14 : Gtk_Menu_Item;
      Menuitem15 : Gtk_Menu_Item;
      Menuitem16 : Gtk_Menu_Item;
      Menuitem17 : Gtk_Menu_Item;
      Hpaned1 : Gtk_Hpaned;
      Vbox5 : Gtk_Vbox;
      Handlebox2 : Gtk_Handle_Box;
      Toolbar4 : Gtk_Toolbar;
      Button10 : Gtk_Widget;
      Button11 : Gtk_Widget;
      Button12 : Gtk_Widget;
      Handlebox3 : Gtk_Handle_Box;
      Notebook6 : Gtk_Notebook;
      Frame18 : Gtk_Frame;
      Toolbar5 : Gtk_Toolbar;
      Togglebutton1 : Gtk_Widget;
      Togglebutton2 : Gtk_Widget;
      Togglebutton3 : Gtk_Widget;
      Togglebutton4 : Gtk_Widget;
      Togglebutton5 : Gtk_Widget;
      Togglebutton6 : Gtk_Widget;
      Togglebutton7 : Gtk_Widget;
      Togglebutton8 : Gtk_Widget;
      Togglebutton9 : Gtk_Widget;
      Togglebutton10 : Gtk_Widget;
      Togglebutton11 : Gtk_Widget;
      Togglebutton12 : Gtk_Widget;
      Togglebutton13 : Gtk_Widget;
      Togglebutton14 : Gtk_Widget;
      Label40 : Gtk_Label;
      Frame19 : Gtk_Frame;
      Label41 : Gtk_Label;
      Frame20 : Gtk_Frame;
      Label42 : Gtk_Label;
      Frame21 : Gtk_Frame;
      Label43 : Gtk_Label;
      Frame22 : Gtk_Frame;
      Label44 : Gtk_Label;
      Scrolledwindow8 : Gtk_Scrolled_Window;
      Ctree1 : Gtk_Ctree;
      Label45 : Gtk_Label;
      Label46 : Gtk_Label;
      Statusbar1 : Gtk_Statusbar;
      Vbox6 : Gtk_Vbox;
      Combo2 : Gtk_Combo;
      Entry1 : Gtk_Entry;
      Notebook7 : Gtk_Notebook;
      Scrolledwindow11 : Gtk_Scrolled_Window;
      Clist6 : Gtk_Clist;
      Label55 : Gtk_Label;
      Label56 : Gtk_Label;
      Label57 : Gtk_Label;
      Scrolledwindow12 : Gtk_Scrolled_Window;
      Clist7 : Gtk_Clist;
      Label58 : Gtk_Label;
      Label59 : Gtk_Label;
      Label60 : Gtk_Label;
   end record;
   type Gui_Builder_Access is access all Gui_Builder_Record'Class;

   procedure Gtk_New (Gui_Builder : out Gui_Builder_Access);
   procedure Initialize (Gui_Builder : access Gui_Builder_Record'Class);

   Gui_Builder : Gui_Builder_Access;

end Gui_Builder_Pkg;
