[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true
Directories=scalable/16x16,scalable/256x256,scalable/emblems,32x32/apps,24x24/apps

[scalable/16x16]
MinSize=1
Size=16
MaxSize=256
Context=Actions
Type=Scalable

[scalable/256x256]
MinSize=1
Size=256
MaxSize=2048
Context=Actions
Type=Scalable

[scalable/emblems]
MinSize=1
Size=16
MaxSize=256
Context=Actions
Type=Scalable

[24x24/apps]
Size=24
Type=Fixed
Context=Applications

[32x32/apps]
Size=32
Type=Fixed
Context=Applications
