-----------------------------------------------------------------------
--                               GNAT Studio                         --
--                                                                   --
--                     Copyright (C) 2001-2025, AdaCore              --
--                                                                   --
-- GPS is free  software;  you can redistribute it and/or modify  it --
-- under the terms of the GNU General Public License as published by --
-- the Free Software Foundation; either version 2 of the License, or --
-- (at your option) any later version.                               --
--                                                                   --
-- This program is  distributed in the hope that it will be  useful, --
-- but  WITHOUT ANY WARRANTY;  without even the  implied warranty of --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU --
-- General Public License for more details. You should have received --
-- a copy of the GNU General Public License along with this library; --
-- if not,  write to the  Free Software Foundation, Inc.,  59 Temple --
-- Place - Suite 330, Boston, MA 02111-1307, USA.                    --
-----------------------------------------------------------------------

--  This package contains target specific parameters.
--  STATIC FILE - No longer generated by configure (TUI uses Alire)

with VSS.Strings;

package Config is

   pragma Style_Checks (Off);

   type Host_Type is (Windows, Unix, VMS, Unknown);
   --  Possible kind of host where GPS is built

   ---------------
   -- Constants --
   ---------------

   Current_Year : constant VSS.Strings.Virtual_String := "2025";
   --  The year to display in copyright notices

   Version : VSS.Strings.Virtual_String := "25.0.0-dev";
   --  Version number - keep in sync with alire.toml

   Target  : constant VSS.Strings.Virtual_String := "";
   --  Target is runtime-detected for TUI (not needed at build time)

   Darwin_Target : constant Boolean := True;
   --  Running on macOS (TODO: runtime detection for cross-platform)

   Prefix : constant String := "";
   --  TUI doesn't install to system directories (Alire manages this)

   Host : constant Host_Type := Unix;
   --  Host kind - macOS/Linux (TODO: runtime detection for Windows)

   Source_Date : constant VSS.Strings.Virtual_String := "2025-11-04";
   --  Build date

   Max_Frame : constant := 500;
   --  Maximum number of frames displayed in the backtrace window

   Max_Tasks : constant := 999;
   --  Maximum number of tasks/threads displayed in the tasks/threads windows

   Max_PD : constant := 99;
   --  Maximum number of protection domains displayed in the
   --  protection domain window.

   Max_Column_Width : constant := 200;
   --  Maximum width (in pixels) for a column in a list

   Need_To_Strip_CR : constant Boolean := False;
   --  True on systems where lines are separated by both LF and CR

   Async_Commands : constant Boolean := True;
   --  True if user commands are handled asynchronousely, to avoid recursion
   --  in the event processing. See design/commands.txt for more details.
   --  This variable is primarily useful for debugging.

   Can_Output : constant Boolean := True;
   --  True if gvd can print text on standard output/error, false if gvd
   --  is a GUI only process (e.g under windows).

   Layout_Width : constant := 20;
   --  Width for the area reserved for the buttons in the source/asm editor

   Exec_Command : constant String := "xterm -e";
   --  Command used to run helpers

   Default_Ps : constant String :=
     "sh -c """"""(ps x 2> /dev/null || ps -u \$USER 2> /dev/null || ps) | cat""""""";
   --  Command used to list processes on a native system. The String is on
   --  its own line to avoid exceeding line length.

   Default_Print_Cmd : constant String := "lp";
   --  Command used to print a file

   Default_Opaque_MDI : constant Boolean := True;
   --  Default value for the MDI opaque preference

   Default_Diff_Cmd : constant String := "diff";
   --  Command used to generate a diff between two files

   Default_Diff3_Cmd : constant String := "diff3";
   --  Command used to generate a diff between three files

   Default_Patch_Cmd : constant String := "patch";
   --  Command used to apply a patch file

   Support_Execution_Window : constant Boolean := True;
   --  Whether separate debugger execution window is supported by the target

   Default_Charset : constant String := "ISO-8859-1";
   --  Default charset for the host, used throughout GPS to convert strings
   --  from outside GPS (e.g. pathnames, compiler output, file contents, ...)
   --  to UTF-8 internally.

end Config;
