------------------------------------------------------------------------------
--                                                                          --
--                         GNAT COMPILER COMPONENTS                         --
--                                                                          --
--                           Make_Test_Window_Pkg                           --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                            $Revision$
--                                                                          --
--                Copyright (C) 2001 Ada Core Technologies, Inc.            --
--                                                                          --
-- GNAT is free software;  you can  redistribute it  and/or modify it under --
-- terms of the  GNU General Public License as published  by the Free Soft- --
-- ware  Foundation;  either version 2,  or (at your option) any later ver- --
-- sion.  GNAT is distributed in the hope that it will be useful, but WITH- --
-- OUT ANY WARRANTY;  without even the  implied warranty of MERCHANTABILITY --
-- or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License --
-- for  more details.  You should have  received  a copy of the GNU General --
-- Public License  distributed with GNAT;  see file COPYING.  If not, write --
-- to  the Free Software Foundation,  59 Temple Place - Suite 330,  Boston, --
-- MA 02111-1307, USA.                                                      --
--                                                                          --
-- GNAT is maintained by Ada Core Technologies Inc (http://www.gnat.com).   --
--                                                                          --
------------------------------------------------------------------------------

with Gtk.Window; use Gtk.Window;
with Gtk.Box; use Gtk.Box;
with Gtk.Label; use Gtk.Label;
with Gtk.GEntry; use Gtk.GEntry;
with Gtk.Check_Button; use Gtk.Check_Button;
with Gtk.Hbutton_Box; use Gtk.Hbutton_Box;
with Gtk.Button; use Gtk.Button;

package Make_Test_Window_Pkg is
   --  "AUnit_Make_Test" main window definition.  Generated by Glade

   type Make_Test_Window_Record is new Gtk_Window_Record with record
      Vbox0 : Gtk_Vbox;
      Hbox1 : Gtk_Hbox;
      Vbox1 : Gtk_Vbox;
      Label1 : Gtk_Label;
      Label2 : Gtk_Label;
      Label3 : Gtk_Label;
      Label4 : Gtk_Label;
      Vbox2 : Gtk_Vbox;
      Name_Entry : Gtk_Entry;
      Description_Entry : Gtk_Entry;
      Override_Tear_Down : Gtk_Check_Button;
      Override_Set_Up : Gtk_Check_Button;
      Hbuttonbox1 : Gtk_Hbutton_Box;
      Ok : Gtk_Button;
      Cancel : Gtk_Button;
      Help : Gtk_Button;
   end record;
   type Make_Test_Window_Access is access all Make_Test_Window_Record'Class;

   procedure Gtk_New (Make_Test_Window : out Make_Test_Window_Access);
   procedure Initialize
     (Make_Test_Window : access Make_Test_Window_Record'Class);

   Make_Test_Window : Make_Test_Window_Access;

end Make_Test_Window_Pkg;
