ifeq ($(SN_PROJECT),)
SN_PROJECT=True

ifeq ($(BASE_DIR),)
   BASE_DIR=$(shell pwd)
   SN_ROOT=True

   internal-clean:
	$(MAKE) clean

   internal-build:
	$(MAKE)

   internal-compile: internal-build
   internal-c: internal-build
   internal-link:
   internal-ada:
endif

SN_BASE_DIR := $(BASE_DIR)
LDFLAGS += -L$(SN_BASE_DIR)/lib -lpafdb $(SN_BASE_DIR)/lib/db_capi.o

ifneq ($(SN_ROOT),True)
   DEPS_PROJECTS += $(SN_BASE_DIR)/sn
endif

endif
