language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=cov
    - TOXENV=sith
matrix:
    allow_failures:
        - env: TOXENV=cov
        - env: TOXENV=sith
        - env: TOXENV=pypy
install:
    - pip install --quiet --use-mirrors tox
    # install python 3.4 from PPA since Travis does not have python 3.4 yet
    - if [ "$TOXENV" = "py34" ]; then
        sudo apt-add-repository -y ppa:fkrull/deadsnakes;
        sudo apt-get update;
        sudo apt-get install python3.4;
      fi
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi
