/*

Copyright (c) 2000, Red Hat, Inc.

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/

   keyword ("ACCEPT", all, kACCEPT);
   keyword ("ACCESS", all, kACCESS);
   keyword ("ADD", all, kADD);
   keyword ("ADDRESS", vs | mf3, kADDRESS);
   keyword ("ADVANCING", all, kADVANCING);
   keyword ("AFTER", all, kAFTER);
   keyword ("ALL", all | copy_replace, kALL);
   keyword ("ALPHABET", ans85 | vs3 | vs4 | sa | x | mf7, kALPHABET);
   keyword ("ALPHABETIC", all, kALPHABETIC);
   keyword ("ALPHANUMERIC", ans85 | vs | sa | x | mf7, kALPHANUMERIC);
   keyword ("ALPHANUMERIC-EDITED", ans85 | vs | sa | x | mf7, kALPHANUMERIC_EDITED);
   keyword ("ALSO", all, kALSO);
   keyword ("ALTER", all, kALTER);
   keyword ("ALTERNATE", all, kALTERNATE);
   keyword ("AND", all, kAND);
   keyword ("ANY", ans85 | vs | sa | x | mf7, kANY);
   keyword ("APPLY", os | vs | dvs, kAPPLY);
   keyword ("ARE", all, kARE);
   keyword ("AREA", all, kAREA);
   keyword ("AREAS", all, kAREAS);
   keyword ("ASCENDING", all, kASCENDING);
   keyword ("ASSIGN", all, kASSIGN);
   keyword ("AT", all, kAT);
   keyword ("AUTHOR", all, kAUTHOR);
   keyword ("AUTO", x | mf3 | ms, kAUTO);
   keyword ("AUTO-SKIP", mf3 | ms, kAUTO_SKIP);
   keyword ("AUTOMATIC", mf1 | ms, kAUTOMATIC);
   keyword ("BACKGROUND-COLOR", x | mf3 | ms, kBACKGROUND_COLOR);
   keyword ("BACKGROUND-COLOUR", mf3, 0);
   keyword ("BEEP", mf3 | ms | rm, kBEEP);
   keyword ("BEFORE", all, kBEFORE);
   keyword ("BEGINNING", os | vs | dvs, kBEGINNING);
   keyword ("BELL", x | mf3 | ms, kBELL);
   keyword ("BINARY", ans85 | vs3 | vs4 | sa | x | mf7 | rm, kBINARY);
   keyword ("BLANK", all, kBLANK);
   keyword ("BLINK", x | mf3 | ms | rm, kBLINK);
   keyword ("BLOCK", all, kBLOCK);
   keyword ("BOTTOM", all, kBOTTOM);
   keyword ("BY", all | copy_replace, kBY);
   keyword ("CALL", all, kCALL);
   keyword ("CALL-CONVENTION", mf1 | ms, kCALL_CONVENTION);
   keyword ("CANCEL", all - dvs, kCANCEL);
   keyword ("CD", all - dvs, kCD);
   keyword ("CF", all, kCF);
   keyword ("CH", all, kCH);
   keyword ("CHAIN", mf3 | ms, kCHAIN);
   keyword ("CHAINING", mf3 | ms, kCHAINING);
   keyword ("CHANGED", os | vs2 | mf3 | dvs, kCHANGED);
   keyword ("CHARACTER", all, kCHARACTER);
   keyword ("CHARACTERS", all, kCHARACTERS);
   keyword ("CLASS", ans85 | vs3 | vs4 | sa | x | mf7, kCLASS);
   keyword ("CLOCK-UNITS", all, kCLOCK_UNITS);
   keyword ("CLOSE", all, kCLOSE);
   keyword ("CODE", all, kCODE);
   keyword ("CODE-SET", all, kCODE_SET);
   keyword ("COL", mf3 | ms, kCOL);
   keyword ("COLLATING", all - mf1 + mf3, kCOLLATING);
   keyword ("COLUMN", all - mf1 + mf3, kCOLUMN);
   keyword ("COMMA", all, kCOMMA);
   keyword ("COMMIT", mf1, kCOMMIT);
   keyword ("COMMON", ans85 | vs3 | vs4 | sa | x | mf7, kCOMMON);
   keyword ("COMMUNICATION", all - dvs, kCOMMUNICATION);
   keyword ("COMP", all, 0);
   keyword ("COMP-0", mf3 | ms, 0);
   keyword ("COMP-1", os | vs | mf7 | rm | dvs, 0);
   keyword ("COMP-2", os | vs | mf7 | dvs, 0);
   keyword ("COMP-3", os | vs | sa | x | mf1 | ms | rm | dvs, 0);
   keyword ("COMP-4", os | vs | sa | mf7 | ms | dvs, 0);
   keyword ("COMP-5", x | mf3, 0);
   keyword ("COMP-6", rm | er, 0);
   keyword ("COMP-X", mf2, 0);
   keyword ("COMPUTATIONAL", all, kCOMPUTATIONAL);
   keyword ("COMPUTATIONAL-0", mf3 | ms, kCOMPUTATIONAL_0);
   keyword ("COMPUTATIONAL-1", os | vs | mf7 | rm | dvs, kCOMPUTATIONAL_1);
   keyword ("COMPUTATIONAL-2", os | vs | mf7 | dvs, kCOMPUTATIONAL_2);
   keyword ("COMPUTATIONAL-3", os | vs | sa | x | mf1 | ms | rm | dvs, kCOMPUTATIONAL_3);
   keyword ("COMPUTATIONAL-4", os | vs | sa | mf7 | ms | dvs, kCOMPUTATIONAL_4);
   keyword ("COMPUTATIONAL-5", x | mf3, kCOMPUTATIONAL_5);
   keyword ("COMPUTATIONAL-6", rm | er, kCOMPUTATIONAL_6);
   keyword ("COMPUTATIONAL-X", mf2, kCOMPUTATIONAL_X);
   keyword ("COMPUTE", all, kCOMPUTE);
   keyword ("CONFIGURATION", all, kCONFIGURATION);
   keyword ("CONSOLE", os | mf1 | ms | dvs, kCONSOLE);
   keyword ("CONTAINS", all, kCONTAINS);
   keyword ("CONTENT", ans85 | vs | sa | x | mf7, kCONTENT);
   keyword ("CONTINUE", ans85 | vs | sa | x | mf7, kCONTINUE);
   keyword ("CONTROL", all - mf1 + mf5, kCONTROL);
   keyword ("CONTROLS", all, kCONTROLS);
   keyword ("CONVERTING", ans85 | vs3 | vs4 | sa | x | mf7, kCONVERTING);
   keyword ("COPY", all, kCOPY);
   keyword ("CORE-INDEX", os | vs2 | dvs, kCORE_INDEX);
   keyword ("CORR", all, 0);
   keyword ("CORRESPONDING", all, kCORRESPONDING);
   keyword ("COUNT", all, kCOUNT);
   keyword ("CRT", x | mf1, kCRT);
   keyword ("CRT-UNDER", mf1, kCRT_UNDER);
   keyword ("CURRENCY", all, kCURRENCY);
   keyword ("CURSOR", x | mf1, kCURSOR);
   keyword ("CYCLE", mf7, kCYCLE);
   keyword ("DATA", all, kDATA);
   keyword ("DATE", all, kDATE);
   keyword ("DATE-COMPILED", all, kDATE_COMPILED);
   keyword ("DATE-WRITTEN", all, kDATE_WRITTEN);
   keyword ("DAY", all, kDAY);
   keyword ("DAY-OF-WEEK", ans85 | vs3 | vs4 | sa | x | mf7, kDAY_OF_WEEK);
   keyword ("DBCS", vs3 | vs4 | sa | mf7, kDBCS);
   keyword ("DE", all, 0);
   keyword ("DEBUGGING", all, kDEBUGGING);
   keyword ("DECIMAL-POINT", all, kDECIMAL_POINT);
   keyword ("DECLARATIVES", all, kDECLARATIVES);
   keyword ("DELETE", all, kDELETE);
   keyword ("DELIMITED", all, kDELIMITED);
   keyword ("DELIMITER", all, kDELIMITER);
   keyword ("DEPENDING", all, kDEPENDING);
   keyword ("DESCENDING", all, kDESCENDING);
   keyword ("DESTINATION", all - dvs, kDESTINATION);
   keyword ("DETAIL", all, kDETAIL);
   keyword ("DISABLE", all - dvs, kDISABLE);
   keyword ("DISK", mf3 | ms, kDISK);
   keyword ("DISP", os | vs2, kDISP);
   keyword ("DISPLAY", all, kDISPLAY);
   keyword ("DISPLAY-1", vs | sa | mf7, kDISPLAY_1);
   keyword ("DIVIDE", all, kDIVIDE);
   keyword ("DIVISION", all, kDIVISION);
   keyword ("DOWN", all, kDOWN);
   keyword ("DUPLICATES", all, kDUPLICATES);
   keyword ("DYNAMIC", all, kDYNAMIC);
   keyword ("ELSE", all, kELSE);
   keyword ("EMPTY-CHECK", mf3 | ms, kEMPTY_CHECK);
   keyword ("ENABLE", all - dvs, kENABLE);
   keyword ("END", all, kEND);
   keyword ("END-ACCEPT", x | mf4, kEND_ACCEPT);
   keyword ("END-ADD", ans85 | vs | sa | x | mf7, kEND_ADD);
   keyword ("END-CALL", ans85 | vs | sa | x | mf7, kEND_CALL);
   keyword ("END-CHAIN", mf5, kEND_CHAIN);
   keyword ("END-COMPUTE", ans85 | vs | sa | x | mf7, kEND_COMPUTE);
   keyword ("END-DELETE", ans85 | vs | sa | x | mf7, kEND_DELETE);
   keyword ("END-DISPLAY", x | mf7, kEND_DISPLAY);
   keyword ("END-DIVIDE", ans85 | vs | sa | x | mf7, kEND_DIVIDE);
   keyword ("END-EVALUATE", ans85 | vs | sa | x | mf7, kEND_EVALUATE);
   keyword ("END-IF", ans85 | vs | sa | x | mf7, kEND_IF);
   keyword ("END-MULTIPLY", ans85 | vs | sa | x | mf7, kEND_MULTIPLY);
   keyword ("END-OF-PAGE", all, kEND_OF_PAGE);
   keyword ("END-PERFORM", ans85 | vs | sa | x | mf7, kEND_PERFORM);
   keyword ("END-READ", ans85 | vs | sa | x | mf7, kEND_READ);
   keyword ("END-RECEIVE", ans85 | vs3 | vs4 | sa | x | mf7, kEND_RECEIVE);
   keyword ("END-RETURN", ans85 | vs | sa | x | mf7, kEND_RETURN);
   keyword ("END-REWRITE", ans85 | vs | sa | x | mf7, kEND_REWRITE);
   keyword ("END-SEARCH", ans85 | vs | sa | x | mf7, kEND_SEARCH);
   keyword ("END-START", ans85 | vs | sa | x | mf7, kEND_START);
   keyword ("END-STRING", ans85 | vs | sa | x | mf7, kEND_STRING);
   keyword ("END-SUBTRACT", ans85 | vs | sa | x | mf7, kEND_SUBTRACT);
   keyword ("END-UNSTRING", ans85 | vs | sa | x | mf7, kEND_UNSTRING);
   keyword ("END-WRITE", ans85 | vs | sa | x | mf7, kEND_WRITE);
   keyword ("ENDING", os | vs | dvs, kENDING);
   keyword ("ENTER", all, kENTER);
   keyword ("ENTRY", os | vs | mf5 | dvs, kENTRY);
   keyword ("ENVIRONMENT", all, kENVIRONMENT);
   keyword ("EOL", x | mf7 | rm, kEOL);
   keyword ("EOP", all, 0);
   keyword ("EOS", x | mf7 | rm, kEOS);
   keyword ("EQUAL", all, kEQUAL);
   keyword ("EQUALS", mf7, kEQUALS);
   keyword ("ERASE", x | mf3 | ms | rm, kERASE);
   keyword ("ERROR", all, kERROR);
   keyword ("ESCAPE", mf3 | ms, kESCAPE);
   keyword ("EVALUATE", ans85 | vs | sa | x | mf7, kEVALUATE);
   keyword ("EVERY", all, kEVERY);
   keyword ("EXAMINE", os | vs2 | dvs, kEXAMINE);
   keyword ("EXCEEDS",  mf7, kEXCEEDS);
   keyword ("EXCEPTION", all, kEXCEPTION);
   keyword ("EXCLUSIVE", mf1 | ms, kEXCLUSIVE);
   keyword ("EXEC", mf2, 0);
   keyword ("EXECUTE", mf2, kEXECUTE);
   keyword ("EXHIBIT", os | vs2 | mf3 | ms | dvs, kEXHIBIT);
   keyword ("EXIT", all, kEXIT);
   keyword ("EXTEND", all, kEXTEND);
   keyword ("EXTERNAL", ans85 | vs3 | vs4 | sa | x | mf2, kEXTERNAL);
   keyword ("FALSE", ans85 | vs | sa | x | mf7, kFALSE);
   keyword ("FD", all, kFD);
   keyword ("FILE", all, kFILE);
   keyword ("FILE-CONTROL", all, kFILE_CONTROL);
   keyword ("FILE-ID", mf4 | ms, kFILE_ID);
   keyword ("FILLER", all, kFILLER);
   keyword ("FINAL", all, kFINAL);
   keyword ("FIRST", all, kFIRST);
   keyword ("FIXED",  mf3, kFIXED);
   keyword ("FOOTING", all, kFOOTING);
   keyword ("FOR", all, kFOR);
   keyword ("FOREGROUND-COLOR", x | mf3 | ms, kFOREGROUND_COLOR);
   keyword ("FOREGROUND-COLOUR", mf3, 0);
   keyword ("FROM", all, kFROM);
   keyword ("FULL", x | mf3 | ms, kFULL);
   keyword ("FUNCTION", ans85 | vs3 | vs4 | sa2 | x | mf7 | copy_replace, kFUNCTION);
   keyword ("GENERATE", all, kGENERATE);
   keyword ("GIVING", all, kGIVING);
   keyword ("GLOBAL", ans85 | vs3 | vs4 | sa | x | mf7, kGLOBAL);
   keyword ("GO", all, kGO);
   keyword ("GOBACK", os | vs | sa | mf5 | dvs, kGOBACK);
   keyword ("GREATER", all, kGREATER);
   keyword ("GRID", mf4, kGRID);
   keyword ("GROUP", all, kGROUP);
   keyword ("HEADING", all, kHEADING);
   keyword ("HIGH-VALUE", all, kHIGH_VALUE);
   keyword ("HIGH-VALUES", all, 0);
   keyword ("HIGHLIGHT", x | mf3 | ms, kHIGHLIGHT);
   keyword ("I-O", all, kI_O);
   keyword ("I-O-CONTROL", all, kI_O_CONTROL);
   keyword ("ID", os | vs | sa | mf7 | dvs, 0);
   keyword ("IDENTIFICATION", all, kIDENTIFICATION);
   keyword ("IF", all, kIF);
   keyword ("IGNORE", mf8, kIGNORE);
   keyword ("IN", all | copy_replace, kIN);
   keyword ("INDEX", all, kINDEX);
   keyword ("INDEXED", all, kINDEXED);
   keyword ("INDICATE", all, kINDICATE);
   keyword ("INITIAL", all, kINITIAL);
   keyword ("INITIALIZE", ans85 | os | vs | x | mf7, kINITIALIZE);
   keyword ("INITIATE", all, kINITIATE);
   keyword ("INPUT", all, kINPUT);
   keyword ("INPUT-OUTPUT", all, kINPUT_OUTPUT);
   keyword ("INSPECT", all, kINSPECT);
   keyword ("INSTALLATION", all, kINSTALLATION);
   keyword ("INTO", all, kINTO);
   keyword ("INVALID", all, kINVALID);
   keyword ("IS", all, kIS);
   keyword ("JUST", all, 0);
   keyword ("JUSTIFIED", all, kJUSTIFIED);
   keyword ("KEPT", mf1, kKEPT);
   keyword ("KEY", all, kKEY);
   keyword ("KEYBOARD", mf3, kKEYBOARD);
   keyword ("LABEL", all, kLABEL);
   keyword ("LAST", all, kLAST);
   keyword ("LEADING", all, kLEADING);
   keyword ("LEFT", all, kLEFT);
   keyword ("LEFT-JUSTIFY", mf3 | ms, kLEFT_JUSTIFY);
   keyword ("LEFTLINE", mf4, kLEFTLINE);
   keyword ("LENGTH", all - dvs - mf1 + mf6 | copy_replace, kLENGTH);
   keyword ("LENGTH-CHECK", mf3 | ms, kLENGTH_CHECK);
   keyword ("LESS", all, kLESS);
   keyword ("LIMIT", all, kLIMIT);
   keyword ("LIMITS", all, kLIMITS);
   keyword ("LINAGE", all, kLINAGE);
   keyword ("LINE", all, kLINE);
   keyword ("LINES", all, kLINES);
   keyword ("LINKAGE", all, kLINKAGE);
   keyword ("LOCAL-STORAGE", mf5, kLOCAL_STORAGE);
   keyword ("LOCK", all, kLOCK);
   keyword ("LOW-VALUE", all, kLOW_VALUE);
   keyword ("LOW-VALUES", all, 0);
   keyword ("LOWER", mf8, kLOWER);
   keyword ("LOWLIGHT", x | mf7, kLOWLIGHT);
   keyword ("MANUAL", mf1 | ms, kMANUAL);
   keyword ("MEMORY", all, kMEMORY);
   keyword ("MERGE", all, kMERGE);
   keyword ("MESSAGE", all - dvs, kMESSAGE);
   keyword ("MODE", all, kMODE);
   keyword ("MODULES", all, kMODULES);
   keyword ("MOVE", all, kMOVE);
   keyword ("MULTIPLE", all, kMULTIPLE);
   keyword ("MULTIPLY", all, kMULTIPLY);
   keyword ("NAME", mf3, kNAME);
   keyword ("NAMED", os | vs2 | mf3 | ms | dvs, kNAMED);
   keyword ("NATIONAL", mf8, kNATIONAL);
   keyword ("NATIONAL-EDITED", mf8, kNATIONAL_EDITED);
   keyword ("NEGATIVE", all, kNEGATIVE);
   keyword ("NEXT", all, kNEXT);
   keyword ("NO", all, kNO);
   keyword ("NO-ECHO", mf3 | ms, kNO_ECHO);
   keyword ("NOT", all, kNOT);
   keyword ("NULL", vs | mf6, kNULL);
   keyword ("NULLS", vs | mf6, kNULLS);
   keyword ("NUMBER", all - mf1 + mf3, kNUMBER);
   keyword ("NUMERIC", all, kNUMERIC);
   keyword ("NUMERIC-EDITED", ans85 | vs | sa | x | mf7, kNUMERIC_EDITED);
   keyword ("OBJECT-COMPUTER", all, kOBJECT_COMPUTER);
   keyword ("OCCURS", all, kOCCURS);
   keyword ("OF", all | copy_replace, kOF);
   keyword ("OFF", all, kOFF);
   keyword ("OMITTED", all, kOMITTED);
   keyword ("ON", all, kON);
   keyword ("OPEN", all, kOPEN);
   keyword ("OPTIONAL", all, kOPTIONAL);
   keyword ("OR", all, kOR);
   keyword ("ORDER", ans85 | vs3 | vs4 | sa | x | mf7, kORDER);
   keyword ("ORGANIZATION", all, kORGANIZATION);
   keyword ("OTHER", ans85 | vs | sa | x | mf7, kOTHER);
   keyword ("OTHERWISE", os | vs2 | dvs, 0);
   keyword ("OUTPUT", all, kOUTPUT);
   keyword ("OVERFLOW", all, kOVERFLOW);
   keyword ("OVERLINE", mf4, kOVERLINE);
   keyword ("PACKED-DECIMAL", ans85 | vs3 | vs4 | sa | x | mf7, kPACKED_DECIMAL);
   keyword ("PADDING", ans85 | vs3 | vs4 | sa | x | mf7, kPADDING);
   keyword ("PAGE", all, kPAGE);
   keyword ("PARAGRAPH", mf7, kPARAGRAPH);
   keyword ("PASSWORD", os | vs | dvs, kPASSWORD);
   keyword ("PERFORM", all, kPERFORM);
   keyword ("PF", all, kPF);
   keyword ("PH", all, kPH);
   keyword ("PIC", all, 0);
   keyword ("PICTURE", all, kPICTURE);
   keyword ("PLUS", all - mf1 + mf3, kPLUS);
   keyword ("POINTER", all, kPOINTER);
   keyword ("POSITION", all, kPOSITION);
   keyword ("POSITIONING", os | vs2 | dvs, kPOSITIONING);
   keyword ("POSITIVE", all, kPOSITIVE);
   keyword ("PREVIOUS", mf3, kPREVIOUS);
   keyword ("PRINTER", mf3 | ms, kPRINTER);
   keyword ("PRINTER-1", mf3, kPRINTER_1);
   keyword ("PRINTING", all, kPRINTING);
   keyword ("PROCEDURE", all, kPROCEDURE);
   keyword ("PROCEDURE-POINTER", c370 | mf5, kPROCEDURE_POINTER);
   keyword ("PROCEDURES", all, kPROCEDURES);
   keyword ("PROCEED", all, kPROCEED);
   keyword ("PROGRAM", all, kPROGRAM);
   keyword ("PROGRAM-ID", all, kPROGRAM_ID);
   keyword ("PROMPT", mf3 | ms | rm, kPROMPT);
   keyword ("PURGE", ans85 | vs3 | sa | x | mf7, kPURGE);
   keyword ("QUEUE", all - dvs, kQUEUE);
   keyword ("QUOTE", all, kQUOTE);
   keyword ("QUOTES", all, 0);
   keyword ("RANDOM", all, kRANDOM);
   keyword ("RD", all, kRD);
   keyword ("READ", all, kREAD);
   keyword ("READY", os | vs | sa | mf3 | ms | dvs, kREADY);
   keyword ("RECEIVE", all - dvs, kRECEIVE);
   keyword ("RECORD", all, kRECORD);
   keyword ("RECORD-OVERFLOW", os | vs2, kRECORD_OVERFLOW);
   keyword ("RECORDING", os | vs | mf3 | dvs, kRECORDING);
   keyword ("RECORDS", all, kRECORDS);
   keyword ("REDEFINES", all, kREDEFINES);
   keyword ("REEL", all, kREEL);
   keyword ("REFERENCE", ans85 | vs | sa | x | mf7, kREFERENCE);
   keyword ("REFERENCES", all, kREFERENCES);
   keyword ("RELATIVE", all, kRELATIVE);
   keyword ("RELEASE", all, kRELEASE);
   keyword ("RELOAD", os | vs | dvs, kRELOAD);
   keyword ("REMAINDER", all, kREMAINDER);
   keyword ("REMARKS", os | vs2 | dvs, kREMARKS);
   keyword ("REMOVAL", all, kREMOVAL);
   keyword ("RENAMES", all, kRENAMES);
   keyword ("REORG-CRITERIA", os | vs2, kREORG_CRITERIA);
   keyword ("REPLACE", ans85 | vs3 | vs4 | sa | x | mf7, kREPLACE);
   keyword ("REPLACING", all, kREPLACING);
   keyword ("REPORT", all, kREPORT);
   keyword ("REPORTING", all, kREPORTING);
   keyword ("REPORTS", all, kREPORTS);
   keyword ("REQUIRED", x | mf3 | ms, kREQUIRED);
   keyword ("RERUN", all, kRERUN);
   keyword ("RESERVE", all, kRESERVE);
   keyword ("RESET", os | vs | sa | mf3 | ms | dvs, kRESET);
   keyword ("RETURN", all, kRETURN);
   keyword ("RETURNING", mf5, kRETURNING);
   keyword ("REVERSE-VIDEO", x | mf3 | ms, kREVERSE_VIDEO);
   keyword ("REVERSED", all, kREVERSED);
   keyword ("REWIND", all, kREWIND);
   keyword ("REWRITE", all, kREWRITE);
   keyword ("RF", all, kRF);
   keyword ("RH", all, kRH);
   keyword ("RIGHT", all, kRIGHT);
   keyword ("RIGHT-JUSTIFY", mf3 | ms, kRIGHT_JUSTIFY);
   keyword ("ROLLBACK", mf1, kROLLBACK);
   keyword ("ROUNDED", all, kROUNDED);
   keyword ("RUN", all, kRUN);
   keyword ("SAME", all, kSAME);
   keyword ("SCREEN", x | mf3 | ms, kSCREEN);
   keyword ("SD", all, kSD);
   keyword ("SEARCH", all, kSEARCH);
   keyword ("SECTION", all, kSECTION);
   keyword ("SECURE", x | mf3 | ms, kSECURE);
   keyword ("SECURITY", all, kSECURITY);
   keyword ("SEGMENT", all - dvs, kSEGMENT);
   keyword ("SEGMENT-LIMIT", all, kSEGMENT_LIMIT);
   keyword ("SELECT", all, kSELECT);
   keyword ("SEND", all - dvs, kSEND);
   keyword ("SENTENCE", all, kSENTENCE);
   keyword ("SEPARATE", all, kSEPARATE);
   keyword ("SEQUENCE", all, kSEQUENCE);
   keyword ("SEQUENTIAL", all, kSEQUENTIAL);
   keyword ("SERVICE", os | vs | dvs, kSERVICE);
   keyword ("SET", all, kSET);
   keyword ("SIGN", all, kSIGN);
   keyword ("SIZE", all, kSIZE);
   keyword ("SORT", all, kSORT);
   keyword ("SORT-MERGE", all, kSORT_MERGE);
   keyword ("SOURCE", all, kSOURCE);
   keyword ("SOURCE-COMPUTER", all, kSOURCE_COMPUTER);
   keyword ("SPACE", all, kSPACE);
   keyword ("SPACE-FILL", mf3 | ms, kSPACE_FILL);
   keyword ("SPACES", all, 0);
   keyword ("SPECIAL-NAMES", all, kSPECIAL_NAMES);
   keyword ("STANDARD", all, kSTANDARD);
   keyword ("STANDARD-1", all, kSTANDARD_1);
   keyword ("START", all, kSTART);
   keyword ("STATUS", all, kSTATUS);
   keyword ("STOP", all, kSTOP);
   keyword ("STRING", all, kSTRING);
   keyword ("SUB-QUEUE-1", all - dvs, kSUB_QUEUE_1);
   keyword ("SUB-QUEUE-2", all - dvs, kSUB_QUEUE_2);
   keyword ("SUB-QUEUE-3", all - dvs, kSUB_QUEUE_3);
   keyword ("SUBTRACT", all, kSUBTRACT);
   keyword ("SUM", all, kSUM);
   keyword ("SUPPRESS", all, kSUPPRESS);
   keyword ("SYMBOLIC", all - dvs, kSYMBOLIC);
   keyword ("SYNC", all, 0);
   keyword ("SYNCHRONIZED", all, kSYNCHRONIZED);
   keyword ("TABLE", all - dvs, kTABLE);
   keyword ("TALLYING", all, kTALLYING);
   keyword ("TAPE", all, kTAPE);
   keyword ("TERMINAL", all - dvs, kTERMINAL);
   keyword ("TERMINATE", all, kTERMINATE);
   keyword ("TEST", ans85 | vs | sa | x | mf7, kTEST);
   keyword ("TEXT", all - dvs, kTEXT);
   keyword ("THAN", all, kTHAN);
   keyword ("THEN", ans85 | os | vs | sa | x | mf1 | dvs, kTHEN);
   keyword ("THROUGH", all, kTHROUGH);
   keyword ("THRU", all, 0);
   keyword ("TIME", all, kTIME);
   keyword ("TIME-OUT", mf7, kTIME_OUT);
   keyword ("TIMEOUT", mf7, 0);
   keyword ("TIMES", all, kTIMES);
   keyword ("TO", all, kTO);
   keyword ("TOP", all, kTOP);
   keyword ("TRACE",  os | vs | mf3 | ms | dvs, kTRACE);
   keyword ("TRAILING", all, kTRAILING);
   keyword ("TRAILING-SIGN", mf3 | ms, kTRAILING_SIGN);
   keyword ("TRANSFORM", os | vs2 | dvs, kTRANSFORM);
   keyword ("TRUE", ans85 | vs | sa | x | mf7, kTRUE);
   keyword ("TYPE", all - dvs, kTYPE);
   keyword ("UNDERLINE", x | mf3 | ms, kUNDERLINE);
   keyword ("UNEQUAL",  mf7, kUNEQUAL);
   keyword ("UNIT", all, 0);
   keyword ("UNLOCK", mf1 | ms | rm, kUNLOCK);
   keyword ("UNSTRING", all, kUNSTRING);
   keyword ("UNTIL", all, kUNTIL);
   keyword ("UP", all, kUP);
   keyword ("UPDATE", mf3 | ms | rm, kUPDATE);
   keyword ("UPON", all, kUPON);
   keyword ("UPPER", mf8, kUPPER);
   keyword ("USAGE", all, kUSAGE);
   keyword ("USE", all, kUSE);
   keyword ("USER", mf3, kUSER);
   keyword ("USING", all, kUSING);
   keyword ("VALUE", all, kVALUE);
   keyword ("VALUES", all, kVALUES);
   keyword ("VARIABLE", mf3, kVARIABLE);
   keyword ("VARYING", all, kVARYING);
   keyword ("WAIT", mf8 | ms, kWAIT);
   keyword ("WHEN", all, kWHEN);
   keyword ("WITH", all, kWITH);
   keyword ("WORDS", all, kWORDS);
   keyword ("WORKING-STORAGE", all, kWORKING_STORAGE);
   keyword ("WRITE", all, kWRITE);
   keyword ("WRITE-ONLY", os | vs | dvs, kWRITE_ONLY);
   keyword ("ZERO", all, kZERO);
   keyword ("ZERO-FILL", mf3 | ms, kZERO_FILL);
   keyword ("ZEROES", all, 0);
   keyword ("ZEROS", all, kZEROS);

