# The purpose of this script is to generate a test harness
# with GNATtest using counterexamples values from SPARK for
# some SPARK check.

import os
import sys
import json
import shutil
import argparse
import os_utils
import subprocess

import GPS

generate_hollow_harness = "Generate Hollow Harness"
gnattest_command = "Run GNATtest"


# Generate a hollow test harness for a subprogram
def run_gnattest(project_name, filename, line, force):
    GPS.BuildTarget(generate_hollow_harness).execute(
        extra_args=[f"--gen-test-subprograms={filename}:{str(line)}"],
        force = force
    )



# Retreive the hash16 that gnattest uses to refer to a subprogram
def get_hash(project_name, filename, line):
    command = [
        "gnattest",
        f"-P{project_name}",
        f"--dump-subp-hash={filename}:{line}",
        "--quiet",
    ]

    proc = GPS.Process(command, capture_output=True, text=True)

    proc.wait()

    return proc.get_result().strip("\n").strip("\t")


# Retreive counterexample values from a .spark file
def get_values_from_spark_JSON(JSON_file, source_file, source_line):
    parts = source_file.split(os.path.sep)
    source_file = parts[-1]
    try:
        with open(JSON_file, "r") as f:
            data = json.load(f)

            proofs = data.get("proof", {})
            for proof in proofs:

                cntexmp_value = proof.get("cntexmp_value", {})

                subp_file = cntexmp_value.get("subp_file")
                subp_line = cntexmp_value.get("subp_line")

                if subp_file == source_file and str(subp_line) == str(source_line):
                    return cntexmp_value.get("inputs", {})

        return None

    except FileNotFoundError:
        GPS.Console().write(f"Error: filename  {JSON_file}  not found.")
        return None
    except json.JSONDecodeError:
        GPS.Console().write(f"Error: Invalid JSON format in {JSON_file}.")
        return None
    except Exception as e:
        GPS.Console().write(f"An unexpected error occurred: {e}")
        return None


# Fill a .json generated by GNATtest with values from SPARK counterexamples
def replace_values(JSON_file, subp_hash, values):
    try:
        with open(JSON_file, "r") as f:
            data = json.load(f)

            subprogram = data.get(subp_hash, {})

            if subprogram == {}:
                GPS.Console().write(
                    "error: hashes do not match"
                )  # This should never happen
                return False

            test_vectors = data.get(subp_hash, {}).get("test_vectors", {})

            test_vectors[0]["origin"] = "GNATprove"

            param_vectors = test_vectors[0].get("param_values", {})

            for value in values:
                name = value.get("name", {})
                val = value.get("value", {})

                for param in param_vectors:
                    if param.get("name", {}) == name:
                        param["value"] = val

        with open(JSON_file, "w") as f:
            json.dump(data, f, indent=4)
            return True

    except FileNotFoundError:
        GPS.Console().write(f"Error: filename {JSON_file} not found.")
        return False
    except json.JSONDecodeError:
        GPS.Console().write(f"Error: Invalid JSON format in {JSON_file}.")
        return False
    except Exception as e:
        GPS.Console().write(f"An unexpected error occurred: {e}")
        return False


# Generate complete test harness from a .json file
def generate_tests(filename, line, force):
    GPS.BuildTarget(gnattest_command).execute(
        extra_args=[f"--gen-test-subprograms={filename}:{str(line)}"],
        force = force
    )


# Split location in (file, line, col)
def parse_subp(s):
    parts = s.split(':')
    if len(parts) == 3 and parts[1].isdigit() and parts[2].isdigit():
        return parts[0], int(parts[1]), int(parts[2])
    return None, None, None


# Performs the testgen pipeline
def run(spec, subp, check_type, package_name, force=False):

    spec_file, spec_line, spec_col = parse_subp(spec)

    subp_file, subp_line, subp_col = parse_subp(subp)

    project_name = str.lower(GPS.Project.root().name())
    
    project_path = GPS.Project.root().file().path

    spark_filenames = []

    GPS.Console().write(f"testgen starting..." + os.linesep)

    found = False
    for f in GPS.Project.root().object_dirs(recursive=False):
        if found:
            break
        for file in os.listdir(os.path.join(f,
                                            "gnatprove")):
            if found:
                break
            if file.endswith(".spark"):
                spark_filenames.append(file)
                artifacts = f
                found = True

    if not found:
        GPS.Console().write("could not find generated .spark file.")
        return

    ce_values = None
    for spark_filename in spark_filenames:
        ce_values = get_values_from_spark_JSON(
            os.path.join(artifacts,
                         "gnatprove",
                         spark_filename),
            spec_file,
            spec_line,
        )
        if ce_values is not None:
            break

    if ce_values is None:
        GPS.Console().write("no counter-example at " + subp_file + ":" + str(subp_line))
        return

    hash_value = get_hash(project_name, os.path.join("src", spec_file), spec_line)

    run_gnattest(project_name, spec_file, spec_line, force)

    json_file = os.path.join(
        artifacts,
        "gnattest",
        "tests",
        "JSON_Tests",
        f"{package_name}.json",
    )

    if not os.path.isfile(json_file):
        GPS.Console().write("Could not generate harness. Aborting.")
        return

    r = replace_values(
        json_file,
        hash_value,
        ce_values,
    )

    if not r:
        GPS.Console().write("Inserting counterexample values into " +
                            "test harness failed. Aborting.")
        return

    generate_tests(spec_file, spec_line, force)

    harness_path = os.path.join(
        artifacts,
        "gnattest",
        "harness",
        "test_driver.gpr")

    GPS.Console().write(f"Test harness has been generated and can be found at {harness_path}")

    GPS.Message("default",
                GPS.File(subp_file),
                subp_line,
                subp_col,
                f"Executable test case for counterexample available at {harness_path}");
