# List of C files to compile
C_FILES=${GVDCOMMON_SRC}/pixmaps/pixmaps.c

# Main file(s) to compile
MAIN=make_browsers

# List of modules we depend on (Check ../../Makefile.common for list of
# supported modules)
MODULES=gtkada kernel common debugger_common prj_editor widgets

include ../../Makefile.common
