# Additional variables and targets suitable for developers.
# This file is optionally included in Makefile and provides additional
# targets for testing.

# Developers settings

# Testsuite executables
CSF_TEST = csf_test
FIND_TEST = find_test
TESTS = $(CSF_TEST)

DEVCLEAN = $(TESTS)

.PHONY: test gen sn_use

dev: all

test : $(TESTS)
	@./$(CSF_TEST)  	\
	&& ./$(SV_TEST) 	\
	&& echo "Test PASSED" 	\
	|| echo "Test FAILED"

$(CSF_TEST): csf_test.o
	$(CC) $(LIBS) $< -o $@ -lpafdb

csf_test.o: csf_test.c
	$(CC) $(INCLUDES) -c $<
