# List of C files to compile
C_FILES=${GVDCOMMON_SRC}/pixmaps/pixmaps.c

# Main file(s) to compile
MAIN=make_widgets

# List of modules we depend on (Check ../../Makefile.common for list of
# supported modules)
MODULES=debugger_common gtkada common

include ../../Makefile.common
