/*

Copyright (c) 2000, Red Hat, Inc.

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/

/* 
 * lexinput.h
 *
 * Copyright (C) 1998 Cygnus Solutions
 * 
 * Description:
 * Implements a set of routines that can be used by scanners (and scanners
 * generated by tools such as GNU flex) for translating character set encodings
 * to ASCII using the Tcl library.
 */

#ifndef LEXINPUT_H
#define LEXINPUT_H

/* Use GNU flex's YYINPUT macro to call this function and make your
   scanner i18n-aware. */
int sn_encoded_input(char *buf, int max_size);

/* This function should be called at the start of each new file being
   lexed. */
void sn_reset_encoding();

#endif /* LEXINPUT_H */

