\input texiplus   @c -*-texinfo-*-
@c %**start of header
@setfilename gvd.info
@settitle Using GPS
@syncodeindex fn cp

@set GPSVersion 0.9.1

@titlepage

@title Using GPS
@subtitle Version @value{GPSVersion}
@subtitle Document revision level $Revision$
@subtitle Date: $Date$
@author ACT-Europe

@page
@vskip 0pt plus 1filll

Copyright @copyright{} 2001-2002, ACT-Europe.
This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

@end titlepage

@ifinfo
@node Top, Introduction, (dir), (dir)
@top Using GPS

Using GPS

GPS, the GNU Integrated Development Environment

Version @value{GPSVersion}

Date: $Date$

Copyright @copyright{} 2001-2002, ACT-Europe.
This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

@menu
* Introduction::
* Description of the Main Windows::
* Editing File::
* Source Navigation::
* Source Browsing::
* Debugging with GPS::
* Preferences/Settings::
* Customization::
* Environment::

@detailmenu
 --- The Detailed Node Listing ---

Description of the main windows

* The Menu Bar::
* The Tool Bar::
* The Work Space::
* The Search Area::
* The Project Explorer::
* The Console::
* The Status Line::

Editing File

* General Information::
* Navigation in the Source Editor::
* Indentation::
* Cross References::
* Using an External Editor::

Source Navigation

* Spec/Body::

Source Browsing

* General Issues::

Debugging with GPS

Preferences/Settings

Customization

* Customizing the Menu Bar::
* Customizing the Tool Bar::
* Changing Colors Fonts and Pixmaps::

Environment

* Command Line Options::
* Environment Variables::
* Files::
* Reporting bugs::

@end detailmenu
@end menu
@end ifinfo

@c --------------------------------------------------------------------
@node Introduction
@chapter Introduction
@c --------------------------------------------------------------------

@noindent
GPS is a complete integrated development environment that gives access
to a wide range of tools. blah blah blah...

@c --------------------------------------------------------------------
@node Description of the Main Windows
@chapter Description of the Main Windows
@c --------------------------------------------------------------------

@menu
* The Menu Bar::
* The Tool Bar::
* The Work Space::
* The Search Area::
* The Project Explorer::
* The Console::
* The Status Line::
@end menu

@node The Menu Bar
@section The Menu Bar
@noindent

@node The Tool Bar
@section The Tool Bar
@noindent

@node The Work Space
@section The Work Space
@noindent

@node The Search Area
@section The Search Area
@noindent

@node The Project Explorer
@section The Project Explorer
@noindent

@node The Console
@section The Console
@noindent

@node The Status Line
@section The Status Line
@noindent

@c --------------------------------------------------------------------
@node Editing File
@chapter Editing File
@c --------------------------------------------------------------------

@menu
* General Information::
* Navigation in the Source Editor::
* Indentation::
* Cross References::
* Using an External Editor::
@end menu

@node General Information
@section General Information
@noindent

@node Navigation in the Source Editor
@section Navigation in the Source Editor
@noindent

Here is the list of key bindings that can be used in the integrated editor:

@subsection Navigation
@table @b
@item Ctrl-p, up
move to previous line

@item Ctrl-n, down
Move to next line

@item Home
Move to beginning of line

@item End
Move to end of line

@item Ctrl-Home
Move to beginning of file

@item Ctrl-End
Move to end of file

@item Page Up
Move one page up

@item Page Down
Move one page down

@item Right/Ctrl-f
Move one character forward

@item Left/Ctrl-b
Move one character backward

@item Ctrl-Right
Move one word forward

@item Ctrl-Left
Move one word backward

@item Ctrl-Up/Down
Move cursor to beginning of previous/next line.

@item Ctrl-PgUp/PgDn
Move cursor left/right by one view width (same as
clicking in scrollbar shaft), cursor set to first character
or object in view.
@end table

@subsection Selection
@table @b
@item Shift-Ctrl-Right-Left
Select one word forward/backward

@item Shift+Ctrl+Up/Down
Extend selection to beginning of prev/next line.

@item Shift+Ctrl+Home/End
Extend selection to beginning/end of buffer.

@item Shift+Ctrl+PgUp/PgDn
Extend selection left/right by one view width

@item Ctrl+A or Ctrl+/
Select whole text buffer

@item Ctrl+\
Deselect whole text buffer.
@end table

@subsection Editing
@table @b
@item Backspace
Delete previous character

@item Ctrl-d or Delete
Delete next character

@item Ctrl-Delete or Alt-d
Delete to end of word

@item Ctrl-Backspace
Delete to start of word

@item Ctrl-k
Delete to end of line

@item Ctrl-u
Delete current line

@item Alt-Space
Delete all whitespaces around cursor, reinsert single space

@item Alt-\
Delete all whitespaces around cursor

@item Ctrl-x or Ctrl-w
Cut to clipboard

@item Ctrl-c
Copy to clipboard

@item Ctrl-s
Save file to disk

@item Ctrl-v or Ctrl-y
Paste from clipboard

@item Ctrl-z
Undo previous insertion/deletion

@item Ctrl-r
Redo previous insertion/deletion

@item Insert
Toggle overwrite mode
@end table

@node Indentation
@section Indentation
@noindent

@c --------------------------------------------------------------------------
@node Cross References
@section Cross References
@c --------------------------------------------------------------------------

@noindent

GPS provides cross-references for all the entities defined in your
application, as well as some advanced browsers like a call graph.
For this to work, it needs some help from external tools, specific to
each of the supported languages.

@table @command
@item Ada
The GNAT compiler itself is used to generate the cross-references
information. This means that you need to compile your application to
get access to this feature or the call graph. GPS doesn't provide
automatic recompilation at the moment, although this is a planned
feature. If your sources have been modified, you should recompile the
modified files.

There are a few special cases where GPS can not find the external file
(called @file{ALI file}) that contains the cross-references
information. Most likely, this is either because you haven't compiled
your sources first, or because the source code has changed since the
@file{ALI file} was generated.

It could also be that you haven't included in the project the object
directories that contain the @file{ALI files}.

In addition, one special case can not be handled automatically. This
is for separate units, whose file name have been krunched through the
@file{gnatkr} command. To handle this, you should force GPS to parse
all the @file{ALI files} in the appropriate object directory. This is
done by right-clicking on the object directory in the explorer
(left-side panel on the main window), and selecting the menu "Parse
all xref information".

@end table


@c --------------------------------------------------------------------------
@node Using an External Editor
@section Using an External Editor
@c --------------------------------------------------------------------------

@noindent

GPS is fully integrated with a number of external editors, in
particular @file{Emacs} and @file{vi}. The choice of the default
external editor is done in the preferences. The following values are
recognized:

@table @file
@item gnuclient
This is the recommended client. It is based on Emacs, but needs an
extra package to be installed. This is the only client that provides a
full integration in GPS, since any extended lisp command can be sent
to the Emacs server.

By default, gnuclient will open a new Emacs frame for every file
that is opened. You might want to add the following code to your
@file{.emacs} file (create one if needed) so that the same Emacs frame
is reused every time:

@smallexample
   (setq gnuserv-frame (car (frame-list)))
@end smallexample

See @url{http://www.hpl.hp.co.uk/people/ange/gnuserv/} for more information.


@item emacsclient
This is a program that is always available if you have installed
Emacs. As opposed to starting a new Emacs every time, it will reuse an
existing Emacs session. It is then extremely fast to open a file.


@item emacs
This client will start a new Emacs session every time a file needs to
be opened. You should use @file{emacsclient} instead, since it is much
faster, and makes it easier to copy and paste between multiple
files. Basically, the only reason to use this external editor is if
your system doesn't support @file{emacsclient}.


@item vim
@file{Vim} is a vi-like editor that provides a number of enhancements,
for instance syntax highlighting for all the languages supported by
GPS. Selecting this external editor will start an xterm (or command
window, depending on your system) with a running vim process editing
the file.

Note that one limitation of this editor is that if GPS needs to open
the same file a second time, it will open a new editor, instead of
reusing the existing one.

Note that this requires that xterm is found in the PATH, and thus is
not currently supported on Windows systems.


@item vi
This editor works exactly like vim, but uses the standard @file{vi}
command instead of @file{vim}.


@item none
No external editor is used, and the contextual menus simply won't
appear.
@end table


In the cases that require an Emacs server, GPS will try several
solutions if no already running server was found. It will first try to
spawn the glide environment distributed with GNAT. If not found in the
PATH, it will then start a standard Emacs.


In the preferences, there are two settings that allow you to select
the external editor (if left to an an empty string, GPS will
automatically select the first editor available on your system) and
whether this editor should always be used every time you double-click
on a file, or whether you need to explicitely select the contextual
menu to open the external editor.

@c --------------------------------------------------------------------
@node Source Navigation
@chapter Source Navigation
@c --------------------------------------------------------------------

@menu
* Spec/Body::
@end menu

@node Spec/Body
@section Spec/Body
@noindent

@c --------------------------------------------------------------------
@node Source Browsing
@chapter Source Browsing
@c --------------------------------------------------------------------

@menu
* General Issues::
@end menu

@node General Issues
@section General Issues
@noindent

@c --------------------------------------------------------------------
@node Debugging with GPS
@chapter Debugging with GPS
@c --------------------------------------------------------------------

@c --------------------------------------------------------------------
@node Preferences/Settings
@chapter Preferences/Settings
@c --------------------------------------------------------------------

@c --------------------------------------------------------------------
@node Customization
@chapter Customization
@c --------------------------------------------------------------------

@menu
* Customizing the Menu Bar::
* Customizing the Tool Bar::
* Changing Colors Fonts and Pixmaps::
@end menu

@node Customizing the Menu Bar
@section Customizing the Menu Bar
@noindent

The GPS menu bar can be customized through an XML file called
@file{custom} in the gps home directory (@file{~/.gps} on Unix
systems).

The format of this file is the following:

@smallexample
<?xml version="1.0"?>

<Custom>

  <Submenu>
    <Title>custom menu</Title>

    <Menuitem>
    <Title>item 1</Title>
      <Action>shell command 1</Action>
    </Menuitem>

    <Submenu>
      <Title>other menu</Title>
      <Menuitem>
        <Title> (etc..)
      </Menuitem>

      <Submenu>
        (...)
      </Submenu>
    </Submenu>
  </Submenu>

  <Submenu>
    <Title>custom menu number 2</Title>
    (...)
  </Submenu>

 </Custom>
@end smallexample

The example above creates a two toplevel menus, named @file{custom menu}
and @file{custom menu number 2}. The first one contains a menu item named
@file{item 1}, which is associated to the shell command @file{shell command
1}, and a submenu named @file{other menu}, and so on.

You can define the accelerator keys for your menus, using underscores
in the titles. Thus, if you want an accelerator on the first letter in
a menu named @file{File}, set its title as @file{_File}.

You can add items or submenus to existing menus, using titles for
menus that already exist. For example, this adds an item named
@file{Robert} to the @file{Edit} menu.

@smallexample
<Submenu>
  <Title>Edit</Title>
  <Menuitem>
    <Title>Robert</Title>
  </Menuitem>
</Submenu>
@end smallexample

Use the @file{/} separator to identify the submenu in a menu. For
example, this adds a submenu named @file{Olga} containing an item named
@file{Item} to the @file{Edit} menu.

@smallexample
<Submenu>
  <Title>Edit/Olga</Title>
  <Menuitem>
    <Title>Item</Title>
  </Menuitem>
</Submenu>
@end smallexample

Adding an item with an empty title or no title at all inserts a
menu separator.

You can use macro arguments to pass to your shell
commands. Macro arguments are special parameters that are transformed
every time that the command is about to be executed. The following
macro arguments exist in GPS:

@table @file
@item %f
Base name of the currently opened file.

@item %F
Absolute name of the currently opened file.

@item %p
The current project.

@item %P
The root project.

@item %(p|P)[r](d|s)[f]
Substituted by the contents of a project :

P : the project is the root project

p : the project is the current project

r : indicates that the listing should be project-recursive, ie that
sub-projects should be listed as well, and their subprojects, and so
on. 

d : list the source directories

s : list the source files

f : output the list into a file and substitute the parameter with the
name of that file. 
@end table

Examples :

@table @file

@item %Ps
Replaced by a list of source files in the root project.

@item %prs
Replaced by a list of files in the current project, and all imported
subprojects, recursively.

@item %prdf
Replaced by the name of a file that contains a list of source
directories in the current project, and all imported subprojects,
recursively.
@end table


@node Customizing the Tool Bar
@section Customizing the Tool Bar
@noindent

@node Changing Colors Fonts and Pixmaps
@section Changing the Colors, Fonts and Pixmaps
@noindent

GPS can be configured through the usual gtk+ mechanisms of @file{rc
files}. The trick is to create a text file called @file{gtkrc} in the
gps home directory (@file{~/.gps} on Unix systems), or as a global
change, in the directory etc/gps in the GPS installation. This file
contains the usual configuration description.

For instance, the following will set the default font for all widgets
in the interface. Note that this font is sometimes overridden by
GPS's own preferences, most notably in the source editor.

@smallexample
gtk-font-name = "Helvetica 9"
@end smallexample

The key shortcuts associated with the menus can be changed dynamically
if you want this behavior. It should be activated explicitely by
setting the following in the configuration file:

@smallexample
gtk-can-change-accels = 1
@end smallexample

Special effects can be achieved easily. For instance, the following
code will change the background color of any button, when it is
pressed. It will also set a background pixmap when it is not pressed.
The style also inherits from the one above, so that the buttons also
use the default font.

@smallexample
pixmap_path "<directory_that_contains_the_pixmap>"
style "button" = "default" @{
  bg_pixmap[NORMAL]="<pixmap_name>"
  bg[ACTIVE]="blue"
@}
class "*GtkButton*" style "button"
@end smallexample

Finally, you can configure the key bindings to suit your habits. In
the editor, you can for instance set @key{Ctrl-V} to scroll forward
one page, as usual under the Emacs editor. The following code takes
care of that. Configuring keys is trickier than the above, since you
need to know the signals that the widgets can receive. Basically, the
most useful will probably be @option{move_cursor}. The first
parameter should be one of @option{pages}, @option{paragraphs},
@option{words}, @option{display-lines} or
@option{logical-positions}. The second parameter is the number of
such units to skip

@smallexample
binding "custombind" @{
   bind "<ctrl>v" @{ "move_cursor" (pages, 1, 0) @}
@}
class "*GtkTextView*" binding : highest "custombind"
@end smallexample

Enabling key bindings similar to the popular Emacs editor is even
easier, since you only have to add the following line to the
configuration file:

@smallexample
gtk-key-theme-name = "Emacs"
@end smallexample

@c --------------------------------------------------------------------
@node Environment
@chapter Environment
@c --------------------------------------------------------------------

@menu
* Command Line Options::
* Environment Variables::
* Files::
* Reporting bugs::
@end menu

@node Command Line Options
@section Command Line Options

@smallexample
Usage:
   gps [options...] [source files] [project file]
@end smallexample

@noindent

@c --------------------------------------------------------------------
@node Environment Variables
@section Environment Variables
@c --------------------------------------------------------------------

@noindent
The following environment variables can be set to override some default
settings in GPS:

@table @samp
   @item GPS_ROOT
Override the default root directory specified when GPS
is built (during the @i{configure} process, see the file @code{INSTALL} in
the GPS sources for more details) to access information such as the location
of the translation files.

   @item GPS_HOME
Override the variable HOME if present. All the configuration files and
directories used by GPS are either relative to $HOME/.gps (%HOME%\.gps
under Windows) if GPS_HOME is not set, or to $GPS_HOME/.gps (respectively
%GPS_HOME%\.gps) if set.

   @item GDK_USE_XFT
If this variable is set to 1, then the fonts used in most parts of gps will be
anti-aliased fonts, provided your Xserver supports the Xft extension, and you
have installed anti-aliased fonts on your system, like the truetype fonts
available at @url{http://keithp.com/~keithp/truetype.tar.gz}

@end table

@c --------------------------------------------------------------------
@node Files
@section Files
@c --------------------------------------------------------------------

@noindent

@table @file
   @item $HOME/.gps
GPS state directory

   @item $HOME/.gps/log
@anchor{log file}
Log file created automatically by GPS

   @item $HOME/.gps/preferences
Contains all the preferences in XML format, as specified in the
preferences menu. See also @file{<prefix>/etc/gps/preferences}.

   @item $HOME/.gps/window_settings
Contains all the settings of the windows (window sizes, pane
offset) in XML format. These settings are saved automatically when quitting
GPS, and loaded automatically at start up. To reset the settings, simply
remove this file.

   @item $HOME/.gps/sessions
Directory containing the debugging sessions.

   @item $HOME/.gps/gtkrc
The theme used by the gtk+ library on which gps is based. It allows you
to configure the colors and fonts used in your
application. @xref{Changing Colors Fonts and Pixmaps}.
See also @file{<prefix>/etc/gps/gtkrc}.

   @item $HOME/.gps/sessions/@i{session}
Each file in the @code{sessions} directory represents a particular session
saved by the user.

   @item $HOME/.gps/traces.cfg
Default configuration for the system traces. This traces are used to analyse
problems with GPS. By default, they are sent to the file @file{$HOME/.gps/log}.

   @item @i{prefix}
The prefix directory where GPS is installed, e.g @file{/opt/gps}.

   @item @i{prefix}/bin
The directory containing the GPS executables.

   @item @i{prefix}/etc/gps
The directory containing global configuration files for GPS.

   @item @i{prefix}/etc/gps/gtkrc
The global theme used by the gtk+ library. See also @file{$HOME/.gps/gtkrc}.

   @item @i{prefix}/etc/gps/pangorc
The pango (generic font handling) configuration file.

   @item @i{prefix}/etc/gps/pangox.aliases
File defining font aliases to X font set.

   @item @i{prefix}/etc/gps/preferences
Global preferences in XML format. See also @file{$HOME/.gps/preferences}.

   @item @i{prefix}/lib
This directory contains the shared libraries used by GPS.

   @item @i{prefix}/doc/gps/html
GPS will look for all the documentation under this directory.

   @item @i{prefix}/share/gps/gps-animation.gif
Animated image displayed in the top right corner of GPS to indicate that
actions (e.g compilation) are on going.

   @item @i{prefix}/share/locale
Directory used to retrieve the translation files, when relevant.

@end table

@c --------------------------------------------------------------------
@node Reporting bugs
@section Reporting bugs
@c --------------------------------------------------------------------

@noindent
If you encounter a bug in GPS, you can report it to
@uref{mailto:report@@gnat.com} if you are a supported user (to become a
supported user, contact @uref{mailto:sales@@gnat.com}), or to the
public gps development list (@uref{mailto:gps-devel@@lists.act-europe.fr}).

Please try to include a detailed description of the problem, including
sources to reproduce it if possible, and/or a scenario describing the
actions performed to reproduce the problem.

@c @printindex cp

@contents

@bye
