\input texiplus   @c -*-texinfo-*-
@c %**start of header
@setfilename gvd.info
@settitle Using Glide 2
@syncodeindex fn cp

@set GlideVersion 0.5

@titlepage

@title Using Glide 2
@subtitle Version @value{GlideVersion}
@subtitle Document revision level $Revision$
@subtitle Date: $Date$
@author ACT-Europe

@page
@vskip 0pt plus 1filll

Copyright @copyright{} 2001-2002, ACT-Europe.
This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

@end titlepage

@ifinfo
@node Top, Introduction, (dir), (dir)
@top Using Glide 2

Using Glide 2

Glide 2, the GNU Integrated Development Environment

Version @value{GlideVersion}

Date: $Date$

Copyright @copyright{} 2001-2002, ACT-Europe.
This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

@menu
* Introduction::
* Description of the Main Windows::
* Editing File::
* Source Navigation::
* Source Browsing::
* Debugging with Glide 2::
* Preferences/Settings::
* Customization::
* Environment::

@detailmenu
 --- The Detailed Node Listing ---

Description of the main windows

* The Menu Bar::
* The Tool Bar::
* The Work Space::
* The Search Area::
* The Project Explorer::
* The Console::
* The Status Line::

Editing File

* General Information::
* Navigation in the Source Editor::
* Indentation::
* Cross References::
* Using an External Editor::

Source Navigation

* Spec/Body::

Source Browsing

* General Issues::

Debugging with Glide 2

Preferences/Settings

Customization

* Customizing the Tool Bar::
* Customizing the Menu Bar::
* Changing Colors Fonts and Pixmaps::

Environment

* Command Line Options::
* Environment Variables::
* Files::
* Reporting bugs::

@end detailmenu
@end menu
@end ifinfo

@c --------------------------------------------------------------------
@node Introduction
@chapter Introduction
@c --------------------------------------------------------------------

@noindent
Glide 2 is a complete integrated development environment that gives access
to a wide range of tools. blah blah blah...

@c --------------------------------------------------------------------
@node Description of the Main Windows
@chapter Description of the Main Windows
@c --------------------------------------------------------------------

@menu
* The Menu Bar::
* The Tool Bar::
* The Work Space::
* The Search Area::
* The Project Explorer::
* The Console::
* The Status Line::
@end menu

@node The Menu Bar
@section The Menu Bar
@noindent

@node The Tool Bar
@section The Tool Bar
@noindent

@node The Work Space
@section The Work Space
@noindent

@node The Search Area
@section The Search Area
@noindent

@node The Project Explorer
@section The Project Explorer
@noindent

@node The Console
@section The Console
@noindent

@node The Status Line
@section The Status Line
@noindent

@c --------------------------------------------------------------------
@node Editing File
@chapter Editing File
@c --------------------------------------------------------------------

@menu
* General Information::
* Navigation in the Source Editor::
* Indentation::
* Cross References::
* Using an External Editor::
@end menu

@node General Information
@section General Information
@noindent

@node Navigation in the Source Editor
@section Navigation in the Source Editor
@noindent

Here is the list of key bindings that can be used in the integrated editor:

@subsection Navigation
@table @b
@item Ctrl-p, up
move to previous line

@item Ctrl-n, down
Move to next line

@item Home
Move to beginning of line

@item End
Move to end of line

@item Ctrl-Home
Move to beginning of file

@item Ctrl-End
Move to end of file

@item Page Up
Move one page up

@item Page Down
Move one page down

@item Right/Ctrl-f
Move one character forward

@item Left/Ctrl-b
Move one character backward

@item Ctrl-Right
Move one word forward

@item Ctrl-Left
Move one word backward

@item Ctrl-Up/Down
Move cursor to beginning of previous/next line.

@item Ctrl-PgUp/PgDn
Move cursor left/right by one view width (same as
clicking in scrollbar shaft), cursor set to first character
or object in view.
@end table

@subsection Selection
@table @b
@item Shift-Ctrl-Right-Left
Select one word forward/backward

@item Shift+Ctrl+Up/Down
Extend selection to beginning of prev/next line.

@item Shift+Ctrl+Home/End
Extend selection to beginning/end of buffer.

@item Shift+Ctrl+PgUp/PgDn
Extend selection left/right by one view width

@item Ctrl+A or Ctrl+/
Select whole text buffer

@item Ctrl+\
Deselect whole text buffer.
@end table

@subsection Editing
@table @b
@item Backspace
Delete previous character

@item Ctrl-d or Delete
Delete next character

@item Ctrl-Delete or Alt-d
Delete to end of word

@item Ctrl-Backspace
Delete to start of word

@item Ctrl-k
Delete to end of line

@item Ctrl-u
Delete current line

@item Alt-Space
Delete all whitespaces around cursor, reinsert single space

@item Alt-\
Delete all whitespaces around cursor

@item Ctrl-x or Ctrl-w
Cut to clipboard

@item Ctrl-c
Copy to clipboard

@item Ctrl-s
Save file to disk

@item Ctrl-v or Ctrl-y
Paste from clipboard

@item Ctrl-z
Undo previous insertion/deletion

@item Ctrl-r
Redo previous insertion/deletion

@item Insert
Toggle overwrite mode
@end table

@node Indentation
@section Indentation
@noindent

@node Cross References
@section Cross References
@noindent

@node Using an External Editor
@section Using an External Editor
@noindent

@c --------------------------------------------------------------------
@node Source Navigation
@chapter Source Navigation
@c --------------------------------------------------------------------

@menu
* Spec/Body::
@end menu

@node Spec/Body
@section Spec/Body
@noindent

@c --------------------------------------------------------------------
@node Source Browsing
@chapter Source Browsing
@c --------------------------------------------------------------------

@menu
* General Issues::
@end menu

@node General Issues
@section General Issues
@noindent

@c --------------------------------------------------------------------
@node Debugging with Glide 2
@chapter Debugging with Glide 2
@c --------------------------------------------------------------------

@c --------------------------------------------------------------------
@node Preferences/Settings
@chapter Preferences/Settings
@c --------------------------------------------------------------------

@c --------------------------------------------------------------------
@node Customization
@chapter Customization
@c --------------------------------------------------------------------

@menu
* Customizing the Tool Bar::
* Customizing the Menu Bar::
* Changing Colors Fonts and Pixmaps::
@end menu

@node Customizing the Tool Bar
@section Customizing the Tool Bar
@noindent

@node Customizing the Menu Bar
@section Customizing the Menu Bar
@noindent

@node Changing Colors Fonts and Pixmaps
@section Changing the Colors, Fonts and Pixmaps
@noindent

Glide can be configured through the usual gtk+ mechanisms of @file{rc
files}. The trick is to create a text file called @file{gtkrc} in the
glide home directory (@file{~/.glide} on Unix systems). This file
contains the usual configuration description.

For instance, the following will set the default font for all widgets
in the interface. Note that this font is sometimes overridden by
Glide's own preferences, most notably in the source editor.

@smallexample
style "default" @{
   font_name="Helvetica 9"
@}
class "*GtkWidget*" style "default"
@end smallexample

Special effects can be achieved easily. For instance, the following
code will change the background color of any button, when it is
pressed. It will also set a background pixmap when it is not pressed.
The style also inherits from the one above, so that the buttons also
use the default font.

@smallexample
pixmap_path "<directory_that_contains_the_pixmap>"
style "button" = "default" @{
  bg_pixmap[NORMAL]="<pixmap_name>"
  bg[ACTIVE]="blue"
@}
class "*GtkButton*" style "button"
@end smallexample

Finally, you can configure the key bindings to suit your habits. In
the editor, you can for instance set @key{Ctrl-V} to scroll forward
one page, as usual under the Emacs editor. The following code takes
care of that. Configuring keys is trickier than the above, since you
need to know the signals that the widgets can receive. Basically, the
most useful will probably be @option{move_cursor}. The first
parameter should be one of @option{pages}, @option{paragraphs},
@option{words}, @option{display-lines} or
@option{logical-positions}. The second parameter is the number of
such units to skip

@smallexample
binding "custombind" @{
   bind "<ctrl>v" @{ "move_cursor" (pages, 1, 0) @}
@}
class "*GtkTextView*" binding : highest "custombind"
@end smallexample

@c --------------------------------------------------------------------
@node Environment
@chapter Environment
@c --------------------------------------------------------------------

@menu
* Command Line Options::
* Environment Variables::
* Files::
* Reporting bugs::
@end menu

@node Command Line Options
@section Command Line Options

@smallexample
Usage:
   glide2 [options...] [source files] [project file]
@end smallexample

@noindent

@c --------------------------------------------------------------------
@node Environment Variables
@section Environment Variables
@c --------------------------------------------------------------------

@noindent
The following environment variables can be set to override some default
settings in Glide 2:

@table @samp
   @item GLIDE_ROOT.
Override the default root directory specified when Glide 2
is built (during the @i{configure} process, see the file @code{INSTALL} in
the Glide sources for more details) to access information such as the location
of the translation files.

   @item GLIDE_HOME.
Override the variable HOME if present. All the configuration files and
directories used by Glide are either relative to $HOME/.glide (%HOME%\.glide
under Windows) if GLIDE_HOME is not set, or to $GLIDE_HOME/.glide (respectively
%GLIDE_HOME%\.glide) if set.

@end table

@c --------------------------------------------------------------------
@node Files
@section Files
@c --------------------------------------------------------------------

@noindent

@table @file
   @item $HOME/.glide
GVD state directory
   @item $HOME/.glide/log
@anchor{log file}
Log file created automatically by Glide

   @item $HOME/.glide/preferences
Contains all the preferences in XML format, as specified in the
preferences menu.

   @item $HOME/.glide/window_settings
Contains all the settings of the windows (window sizes, pane
offset) in XML format. These settings are saved automatically when quitting
Glide, and loaded automatically at start up. To reset the settings, simply
remove this file.

   @item $HOME/.glide/sessions
Directory containing the debugging sessions.

   @item $HOME/.glide/sessions/@i{session}
Each file in the @code{sessions} directory represents a particular session
saved by the user.

@end table

@c --------------------------------------------------------------------
@node Reporting bugs
@section Reporting bugs
@c --------------------------------------------------------------------

@noindent
If you encounter a bug in Glide, you can report it to
@uref{mailto:report@@gnat.com} if you are a supported user (to become a
supported user, contact @uref{mailto:sales@@gnat.com}), or to the
public glide development list (@uref{mailto:glide-devel@@lists.act-europe.fr}).

Please try to include a detailed description of the problem, including
sources to reproduce it if possible, and/or a scenario describing the
actions performed to reproduce the problem.

@c @printindex cp

@contents

@bye
