
MAIN=kernel
MODULES=kernel gnat gtkada common gvd src_editor prj_editor
# This forces compilation of all files separately, without compiling the
# dependencies, which is just what we want.
NO_STYLE_FILES=glide_*.adb

include ../../Makefile.common
