
C_FILES=${GVDCOMMON_SRC}/pixmaps/pixmaps.c prj_pixmaps.c env.c
MAIN=prj_editor prj_wizard
MODULES=gnat gtkada common debugger_common kernel
NO_STYLE_FILES=
MODULE_LIB=${GVDCOMMON_SRC}/gnat/gexpect_tty.o

include ../../Makefile.common
