
#C_FILES=${GVD_SRC}/pixmaps/pixmaps.c ../src/prj_pixmaps.c
#MAIN=test_scenario normalize test_wizard test_directory
#MODULES=gtkada gnat common gvd prj_editor
#C_FILES=../src/prj_pixmaps.c
C_FILES=
MAIN=test_scenario normalize test_wizard test_directory 
MODULES=kernel gtkada gnat common  debugger_common
NO_STYLE_FILES=
OBJ_DIR=.

include ../../Makefile.common
