ifeq ($(EXPECT_LAUNCHER),)
EXPECT_LAUNCHER=True

ifeq ($(BASE_DIR),)
   BASE_DIR=$(shell pwd)
   EXPECT_ROOT=True

   internal-clean:
	$(MAKE) clean

   internal-build:
	$(MAKE)

   internal-compile: internal-build
   internal-c: internal-build
   internal-link:
   internal-ada:
endif

EXPECT_BASE_DIR := $(BASE_DIR)

ifneq ($(EXPECT_ROOT),True)
   DEPS_PROJECTS += $(EXPECT_BASE_DIR)/expect
endif

endif
