\input texinfo  @c -*-texinfo-*-

@set Version 0.1
@set Title   CoreLib: Library for Ada applications

@settitle @value{Title}
@syncodeindex fn cp

@titlepage
@title @value{Title}
@subtitle Version @value{Version}
@author AdaCore
@page
@vskip 0pt plus 1filll

Copyright @copyright{} 2007, AdaCore

This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.
@end titlepage

@ifnottex
@node Top,, (dir), (dir)
@top @value{Version}

@value{Version}

Version @value{Version}

Copyright @copyright{} 2007, AdaCore

This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

@menu
* Introduction::

@detailmenu
 --- The Detailed Node Listing ---

Introduction

@end detailmenu
@end menu
@end ifnottex

@iftex
@contents
@end iftex

@c -----------------------------------------------------------------------
@node Introduction
@chapter Introduction
@c -----------------------------------------------------------------------

@noindent
The CoreLib library 

@bye

