with Gtk.Window; use Gtk.Window;
with Gtk.Box; use Gtk.Box;
with Gtk.Notebook; use Gtk.Notebook;
with Gtk.Frame; use Gtk.Frame;
with Gtk.Check_Button; use Gtk.Check_Button;
with Gtk.Label; use Gtk.Label;
with Gtk.GEntry; use Gtk.GEntry;
with Gtk.Table; use Gtk.Table;
with Gtk.Combo; use Gtk.Combo;
with Gtk.GEntry; use Gtk.GEntry;
with Gtk.Toolbar; use Gtk.Toolbar;
with Gtk.Adjustment; use Gtk.Adjustment;
with Gtk.Spin_Button; use Gtk.Spin_Button;
with Gtk.Hbutton_Box; use Gtk.Hbutton_Box;
with Gtk.Button; use Gtk.Button;
with Gtk.Object; use Gtk.Object;
package General_Preferences_Pkg is

   type General_Preferences_Record is new Gtk_Window_Record with record
      Vbox2 : Gtk_Vbox;
      Notebook1 : Gtk_Notebook;
      Frame1 : Gtk_Frame;
      Vbox25 : Gtk_Vbox;
      Break_Exception_Check : Gtk_Check_Button;
      Statusbar_Hbox : Gtk_Hbox;
      Label212 : Gtk_Label;
      Statusbar_Timeout_Entry : Gtk_Entry;
      Label213 : Gtk_Label;
      Language_Frame : Gtk_Frame;
      Language_Table : Gtk_Table;
      Label214 : Gtk_Label;
      Label215 : Gtk_Label;
      Label216 : Gtk_Label;
      Ada_Extensions_Entry : Gtk_Entry;
      C_Extensions_Entry : Gtk_Entry;
      Cpp_Extensions_Entry : Gtk_Entry;
      Label_General : Gtk_Label;
      Vbox18 : Gtk_Vbox;
      Frame16 : Gtk_Frame;
      Table9 : Gtk_Table;
      Display_Explorer_Check : Gtk_Check_Button;
      Label75 : Gtk_Label;
      File_Name_Bg_Combo : Gtk_Combo;
      Combo_Entry6 : Gtk_Entry;
      Frame17 : Gtk_Frame;
      Table10 : Gtk_Table;
      Label76 : Gtk_Label;
      Editor_Font_Combo : Gtk_Toolbar;
      Label81 : Gtk_Label;
      Keyword_Color_Combo : Gtk_Combo;
      Combo_Entry11 : Gtk_Entry;
      String_Color_Combo : Gtk_Combo;
      Combo_Entry9 : Gtk_Entry;
      Label80 : Gtk_Label;
      Comment_Color_Combo : Gtk_Combo;
      Combo_Entry10 : Gtk_Entry;
      Label79 : Gtk_Label;
      Strip_Cr_Check : Gtk_Check_Button;
      Syntax_Highlight_Check : Gtk_Check_Button;
      Show_Line_Numbers_Check : Gtk_Check_Button;
      Show_Lines_Code_Check : Gtk_Check_Button;
      Tooltips_Check : Gtk_Check_Button;
      Frame18 : Gtk_Frame;
      Hbox7 : Gtk_Hbox;
      Label82 : Gtk_Label;
      Asm_Highlight_Combo : Gtk_Combo;
      Combo_Entry12 : Gtk_Entry;
      Label_Source : Gtk_Label;
      Frame3 : Gtk_Frame;
      Table3 : Gtk_Table;
      Label83 : Gtk_Label;
      Detect_Aliases_Check : Gtk_Check_Button;
      Align_Grid_Check : Gtk_Check_Button;
      Label84 : Gtk_Label;
      Label85 : Gtk_Label;
      Label86 : Gtk_Label;
      Label87 : Gtk_Label;
      Label88 : Gtk_Label;
      Label89 : Gtk_Label;
      Label90 : Gtk_Label;
      Hide_Big_Items_Check : Gtk_Check_Button;
      Label91 : Gtk_Label;
      Big_Item_Spin : Gtk_Spin_Button;
      Display_Grid_Check : Gtk_Check_Button;
      Title_Font_Combo : Gtk_Toolbar;
      Value_Font_Combo : Gtk_Toolbar;
      Type_Font_Combo : Gtk_Toolbar;
      Xref_Color_Combo : Gtk_Combo;
      Combo_Entry13 : Gtk_Entry;
      Change_Color_Combo : Gtk_Combo;
      Combo_Entry15 : Gtk_Entry;
      Thaw_Bg_Color_Combo : Gtk_Combo;
      Combo_Entry16 : Gtk_Entry;
      Title_Color_Combo : Gtk_Combo;
      Combo_Entry14 : Gtk_Entry;
      Freeze_Bg_Color_Combo : Gtk_Combo;
      Combo_Entry17 : Gtk_Entry;
      Show_Stack_Check : Gtk_Check_Button;
      Look_3d_Check : Gtk_Check_Button;
      Separate_Data_Check : Gtk_Check_Button;
      Label_Data : Gtk_Label;
      Frame13 : Gtk_Frame;
      Table8 : Gtk_Table;
      Label92 : Gtk_Label;
      Label93 : Gtk_Label;
      Debug_Font_Combo : Gtk_Toolbar;
      Debug_Highlight_Combo : Gtk_Combo;
      Combo_Entry24 : Gtk_Entry;
      Label_Command : Gtk_Label;
      Frame19 : Gtk_Frame;
      Table11 : Gtk_Table;
      Label206 : Gtk_Label;
      Label207 : Gtk_Label;
      Memory_Font_Combo : Gtk_Toolbar;
      Memory_Default_Combo : Gtk_Combo;
      Combo_Entry26 : Gtk_Entry;
      Label210 : Gtk_Label;
      Label209 : Gtk_Label;
      Label208 : Gtk_Label;
      Memory_Highlight_Combo : Gtk_Combo;
      Combo_Entry27 : Gtk_Entry;
      Memory_Selection_Combo : Gtk_Combo;
      Entry23 : Gtk_Entry;
      Memory_Modified_Combo : Gtk_Combo;
      Entry24 : Gtk_Entry;
      Label_Memory : Gtk_Label;
      Frame6 : Gtk_Frame;
      Table6 : Gtk_Table;
      Edit_Source_Entry : Gtk_Entry;
      List_Processes_Entry : Gtk_Entry;
      Remote_Shell_Entry : Gtk_Entry;
      Remote_Copy_Entry : Gtk_Entry;
      Label43 : Gtk_Label;
      Label44 : Gtk_Label;
      Label45 : Gtk_Label;
      Label48 : Gtk_Label;
      Label211 : Gtk_Label;
      Html_Entry : Gtk_Entry;
      Label_Helpers : Gtk_Label;
      Hbuttonbox6 : Gtk_Hbutton_Box;
      Ok_Button : Gtk_Button;
      Test_Button : Gtk_Button;
      Cancel_Button : Gtk_Button;
   end record;
   type General_Preferences_Access is access all General_Preferences_Record'Class;

   procedure Gtk_New (General_Preferences : out General_Preferences_Access);
   procedure Initialize (General_Preferences : access General_Preferences_Record'Class);

end General_Preferences_Pkg;
