#!/bin/bash

argv=()
argv[0]="-pwd$PWD"
i=1
directlaunch=0

# making sure file paths are preserved, by using their full path
for arg in "$@"; do
    case "$arg" in
      -*) argv[$i]="$arg" ;;
      *)  argv[$i]="`echo $(cd $(dirname "$arg"); pwd)/$(basename "$arg")`" ;;
    esac
    i=$((i + 1))
done

open -a GPS -n -W --args "${argv[@]}"
