#!/bin/bash

app=$2
resources=$app/Contents/Resources
macos=$app/Contents/MacOS

DYLD_LIBRARY_PATH=$macos/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH

pixbuf_base="$macos/lib/gdk-pixbuf-2.0/2.10.0"
GDK_PIXBUF_MODULE_FILE="$pixbuf_base/loaders.cache"
GDK_PIXBUF_MODULEDIR="$pixbuf_base/loaders"
export GDK_PIXBUF_MODULE_FILE GDK_PIXBUF_MODULEDIR

$macos/bin/gdk-pixbuf-query-loaders > "$GDK_PIXBUF_MODULE_FILE"

cp $resources/gps_cmdline.sh /usr/local/bin/gps
chmod a+x /usr/local/bin/gps

# performs cleanup of launch services to prevent duplicated entry for GPS.app in
# the supported file's contextual menu from the Finder
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
