# List of C files to compile
C_FILES=${GVDCOMMON_SRC}/pixmaps/pixmaps.c
OBJ_DIR=.


# Main file(s) to compile
MAIN=test_vcs

# List of modules we depend on (Check ../../Makefile.common for list of
# supported modules)
MODULES=debugger_common common vcs widgets gtkada

include ../../Makefile.common
